### PR TITLE
Homework16

### PR DESCRIPTION
**Pull request by BohdanaSabada**
I don't know how to do :(

### CODE REVIEW

**Comment by BohdanaSabada** [comment]
updated Homework16

**Comment by Berichicko** [comment]
The code is not compiled! Please finish the homework!You got this problem, please correct it.

image

**HINT**

**How to analyze the error:**

Problems tool window (File Project Errors):
The Current File tab shows the list of problems in the file that is open in the editor. Select a problem and press Enter or double-click to navigate to it. You can also open a preview right in the tool window, and you can use the eye icon to filter the problems by type and to change the sorting.

You can select any problem in the window and press F4  or double-click it to jump to the corresponding line in the editor.

For example 
image

The light bulb icon on the toolbar turns on if there are quick fixes for the selected problem. You can also press Alt+Enter on a problem to see the list of available quick fixes.

image

image

image

https://github.com/Angelina0504/A53-QA-Automation-Framework/assets/104761482/56b1cb3a-8f19-4764-bc48-fe355d79d9d4

**Step 1**

Please, сheck for Balanced Brackets in an code (well-formedness) 

Screenshot_1

**Step 2**

**According to the Java style guide:** 

1. Class names should be nouns, in mixed cases with the first letter of each internal word capitalized. Interfaces names should also be capitalized just like class names.
2. Use whole words and must avoid acronyms and abbreviations.

Rename refactorings https://www.jetbrains.com/help/idea/rename-refactorings.html#rename_class_example

image

image

**Step 3**

You got this problem, please correct it.

Screenshot_2


Screenshot_3

**Solution**

```
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.testng.Assert;
import org.testng.annotations.Test;

import java.time.Duration;

public class LoginTests extends BaseTest {

    @Test
    public void loginEmptyEmailPassword() {

//      Added ChromeOptions argument below to fix websocket error
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--remote-allow-origins=*");

        WebDriver driver = new ChromeDriver(options);
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));

        String url = "https://testpro.io/";
        driver.get(url);
        Assert.assertEquals(driver.getCurrentUrl(), url);
        driver.quit();
    }

    //Happy Path
    @Test
    public void loginValidEmailPassword() throws InterruptedException {

        //Pre-Condition
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--remote-allow-origins=*");

        WebDriver driver = new ChromeDriver(options);
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
        driver.manage().window().maximize();
        //Step1
        String url = "https://qa.koel.app/";
        driver.get(url);
        Thread.sleep(2000);
        //Step2
        WebElement emailField = driver.findElement(By.cssSelector("input[type='email']"));
        emailField.clear();
        emailField.sendKeys("demo@testpro.io");
        Thread.sleep(2000);
        //Step3
        WebElement passwordField = driver.findElement(By.cssSelector("input[type='password']"));
        passwordField.clear();
        passwordField.sendKeys("te$t$tudent");
        Thread.sleep(2000);
        //Step4
        WebElement loginBtn = driver.findElement(By.cssSelector("button[type='submit']"));
        loginBtn.click();
        Thread.sleep(2000);
        //Avatar Icon for Actual vs Expected
        WebElement avatarIcon = driver.findElement(By.cssSelector("img[class='avatar']"));
        //Assertion - Expected vs Actual
        Assert.assertTrue(avatarIcon.isDisplayed());
        //QuitBrowser
        driver.quit();
    }


    //Not so happy Path - Negative Test Case
    @Test
    public void LoginWithInvalidEmailValidPassword() throws InterruptedException {
        //Pre-Condition
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--remote-allow-origins=*");

        WebDriver driver = new ChromeDriver(options);
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
        driver.manage().window().maximize();
        //Step1
        String url = "https://qa.koel.app/";
        driver.get(url);
        Thread.sleep(2000);
        //Step2
        WebElement emailField = driver.findElement(By.cssSelector("input[type='email']"));
        emailField.clear();
        emailField.sendKeys("Invalid@koel.io");
        Thread.sleep(2000);
        //Step3
        WebElement passwordField = driver.findElement(By.cssSelector("input[type='password']"));
        passwordField.clear();
        passwordField.sendKeys("InvalidPassword");
        Thread.sleep(2000);
        //Step4
        WebElement loginBtn = driver.findElement(By.cssSelector("button[type='submit']"));
        loginBtn.click();
        Thread.sleep(2000);
        //Expected Results - Assertions
        Assert.assertEquals(driver.getCurrentUrl(), url);

        //Quit
        driver.quit();

    }

}
```

**Comment by BohdanaSabada** [comment]
updated hw16

**Comment by BohdanaSabada** [comment]
updated HW16

**Comment by BohdanaSabada** [comment]
I did it HW again, please check if everything looks good

**Pull request closed without merging**
